# Site settings
title: Xinyu's Website
description: Xinyu's Website - Jekyll
keywords: Blogging, Fun
author: Xinyu Feng
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://github.com/lyrafeng/lyrafeng.github.io.git" # the base hostname & protocol for your site
