# Site settings
title: Modern Blog
description: Modern-Blog for Jekyll
keywords: Modern, Blogging, Fun
author: Xinyu Feng
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://github.com/lyrafeng/lyrafeng.github.io.git"" # the base hostname & protocol for your site
